name: Publish PostGIS ARM64v8 CI
on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * 1'

defaults:
  run:
    shell: bash

jobs:
  make-docker-images:
    runs-on: ubuntu-20.04
    env:
      VERSION: 10-2.5
    name: Build PostGIS image ${{env.VERSION}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: postgis:${{env.VERSION}}